### ISSUE TITLE
Administration should allow configuration of categories

### ISSUE THREAD

**Issue by timwis** [timwis/jkan#69]

**Comment by JJediny** [comment]
Would moving categories to `_data/categories.yml` instead of `_config.yml` allow for this?

**Comment by timwis** [comment]
Oh, I hadn't thought of that. Currently, the `/admin` page lets you edit settings in the `_config.yml` file, though it uses regex to do it. A distinct `categories.yml` file would probably be easier as we could serialize the YAML and replace the whole file.

Note that we'll probably want to change the structure of `categories_list` to something like:
```yaml
categories_list:
  - name: Education
    image: /img/education.png
  - name: Finance / Budget
    image: /img/finance-budget.png
```
per @abhinemai's idea of putting category images on the front page
